export const lightTheme = {
    statusBarIcons: "dark-content",
    background: "#eee",
    text: "#000000",
    cardBg: "#fff",
    cardTitle: "#333",
    cardPrice: "#666",
    border: "#ddd",
    searchBg: "#ddd",
    searchText: "#ddd",
    tabBarBg: "#ddd",
    tabBarIcon: "#aaa",
    tabBarIconActive: "#333",
    tabBarPaddingVertical: 10,
    tabBarRadius: 50,
    tabBarMarginBottom: 15,
    tabBarMarginHorizontal: 20,
    cartBagBtn: "#fff",
    cartBagBtnIcon: "#111",
    customButtonBg: "#111",
    customButtonText: "#eee",
    getStartedScreenBg: "#ddd",
};

export const darkTheme = {
    statusBarIcons: "light-content",
    background: "#121212",
    text: "#ddd",
    cardBg: "#222",
    cardTitle: "#ddd",
    cardPrice: "#aaa",
    border: "#333",
    searchBg: "#222",
    searchText: "#eee",
    tabBarBg: "#333",
    tabBarIcon: "#aaa",
    tabBarIconActive: "#fff",
    tabBarPaddingVertical: 20,
    tabBarRadius: 0,
    tabBarMarginBottom: 0,
    tabBarMarginHorizontal: 0,
    cartBagBtn: "#222",
    cartBagBtnIcon: "#eee",
    customButtonBg: "#eee",
    customButtonText: "#111",
    getStartedScreenBg: "#333",
};
